import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Container from "../components/Container";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ClientProviders } from "@/components/ClientProviders";
// ...existing code...

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          <Toaster />
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-1">
              <Container>{children}</Container>
            </main>
            <Footer />
          </div>
        </ClientProviders>
      </body>
    </html>
  );
}
